config/routes.rb
Atlus::Application.routes.draw do
  match "/snipets/update_cache" => "snipets#update_cache"

  resources :dashboards

  resources :snipets

  root :controller => "dashboards", :action => "index"

end

app/models/access_log.rb
class AccessLog
  include Mongoid::Document
  field :host, :type => String
  field :user, :type => String
  field :method, :type => String
  field :path, :type => String
  field :code, :type => Integer
  field :size, :type => Integer
  field :referer, :type => String
  field :agent, :type => String
  field :time, :type => Time
end

app/models/book.rb
class Book
  include Mongoid::Document
  field :isbn, :type => String
  field :title, :type => String
  field :author, :type => String
  field :seriesName, :type => String
  field :publishName, :type => String
  field :genre, :type => String
  field :salesDate, :type => String
end

app/models/dashboard.rb
class Dashboard
  include Mongoid::Document
  field :name, :type => String
  field :orders, :type => String, :default => ""
  has_and_belongs_to_many :snipets, inverse_of: nil
end

app/models/data_manager.rb
require 'singleton'
require 'digest/md5'

class DataManager
  include Singleton

  def initialize
    @cache = {}
  end

  def execute query
    key = Digest::MD5.hexdigest query
    if @cache.key? key
      @cache[key]
    else
      @cache[key] = eval(query)
      @cache[key]
    end
  end

  def update query
    key = Digest::MD5.hexdigest query
    @cache[key] = eval(query)
    @cache[key]
  end

end

app/models/response_time.rb
class ResponseTime
  include Mongoid::Document
  field :domain, :type => String
  field :datetime, :type => Time
  field :response, :type => Float
  field :count, :type => Integer
end

app/models/snipet.rb
class Snipet
  include Mongoid::Document
  field :name, :type => String
  field :query, :type => String
  field :chartType, :type => String
  field :width, :type => Integer, :default => 600
  field :height, :type => Integer, :default => 384
  field :isTableVisible, :type => Boolean
  field :isChartVisible, :type => Boolean
  field :scale, :type => Integer, :default => 1
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dashboards }
    end
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
    @dashboards = Dashboard.all
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dashboard }
    end
  end

  # GET /dashboards/new
  # GET /dashboards/new.json
  def new
    @dashboard = Dashboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dashboard }
    end
  end

  # GET /dashboards/1/edit
  def edit
    @dashboard = Dashboard.find(params[:id])
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(params[:dashboard])

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render json: @dashboard, status: :created, location: @dashboard }
      else
        format.html { render action: "new" }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dashboards/1
  # PUT /dashboards/1.json
  def update
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      if @dashboard.update_attributes(params[:dashboard])
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard = Dashboard.find(params[:id])
    @dashboard.destroy

    respond_to do |format|
      format.html { redirect_to dashboards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/snipets_controller.rb
class SnipetsController < ApplicationController
  # GET /snipets
  # GET /snipets.json
  def index
    @snipets = Snipet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snipets }
    end
  end

  # GET /snipets/1
  # GET /snipets/1.json
  def show
    @snipet = Snipet.find(params[:id])
    begin
      @data = DataManager.instance.execute(@snipet.query)
      p @data
      begin
        @table_recods = @data.map{|r| r.map{|x| "<td>#{x}</td>" }.join() }.map{|r| "<tr>#{r}</tr>"}.join
      rescue
        @table_records = ""
        flash[:notice] = "Format Error."
      end 
    rescue TypeError
      @data = []
      flash[:notice] = "Type Error."
    rescue NameError
      @data = []
      flash[:notice] = "Name Error."
    rescue SyntaxError
      @data = []
      flash[:notice] = "Syntax Error."
    end 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @snipet }
    end
  end

  # GET /snipets/new
  # GET /snipets/new.json
  def new
    @snipet = Snipet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snipet }
    end
  end

  # GET /snipets/1/edit
  def edit
    @snipet = Snipet.find(params[:id])
  end

  # POST /snipets
  # POST /snipets.json
  def create
    @snipet = Snipet.new(params[:snipet])

    respond_to do |format|
      if @snipet.save
        format.html { redirect_to @snipet, notice: 'Snipet was successfully created.' }
        format.json { render json: @snipet, status: :created, location: @snipet }
      else
        format.html { render action: "new" }
        format.json { render json: @snipet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /snipets/1
  # PUT /snipets/1.json
  def update
    @snipet = Snipet.find(params[:id])

    respond_to do |format|
      if @snipet.update_attributes(params[:snipet])
        format.html { redirect_to @snipet, notice: 'Snipet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @snipet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snipets/1
  # DELETE /snipets/1.json
  def destroy
    @snipet = Snipet.find(params[:id])
    @snipet.destroy

    respond_to do |format|
      format.html { redirect_to snipets_url }
      format.json { head :no_content }
    end
  end

  def update_cache
    results = {}
    Snipet.find(:all).map do |snipet|
      logger.info("EVENT_NAME:UPDATE_CACHE\tTYPE:START\tQUERY_NAME:#{snipet.name}")
      DataManager.instance.execute(snipet.query)
      logger.info("EVENT_NAME:UPDATE_CACHE\tTYPE:END\tQUERY_NAME:#{snipet.name}")
      results[snipet.name] = "success"
    end

    respond_to do |format|
      format.json { render json:results }
    end
 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/snipets_helper.rb
module SnipetsHelper
end

app/views/dashboards/_form.html.erb
<%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
     <%= f.label :snipets %><br />
     <%= f.select :snipet_ids, Snipet.all.to_a.map{|x| [x.name, x._id]}, {}, {:multiple => true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboards/edit.html.erb
<h1>Editing dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/index.html.erb
<div id="box">
  <nav id="leftBox">
    <ul>
    <% @dashboards.each do |dashboard| %>
      <li>
        <%= link_to dashboard.name, dashboard %>
      </li>
    <% end %>
    </ul>
  </nav>
  <div id="main">
    <ul>
      <li><%= link_to 'New Dashboard', new_dashboard_path %></li>
      <li><%= link_to 'New Snipet', new_snipet_path %></li>
    </ul>
  </div>
</div>

app/views/dashboards/new.html.erb
<h1>New dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboards_path %>

app/views/dashboards/show.html.erb
<div id="box">
  <nav id="leftBox">
    <ul>
    <% @dashboards.each do |dashboard| %>
      <li>
        <%= link_to dashboard.name, dashboard %>
      </li>
    <% end %>
    </ul>
  </nav>
  <div id="main">
    <ul id="toolbar">
      <li><%= link_to 'Edit', edit_dashboard_path(@dashboard) %></li>
      <li><%= link_to 'Destroy', @dashboard, confirm: 'Are you sure?', method: :delete %></li>
      <li><a href="#" onclick="updateOrder()">Save Order</a></li>
    </ul>
    <p id="notice"><%= notice %></p>
    <h1><%= @dashboard.name %></h1>

    <div id="snipets">
      <input type="hidden" id="snipets_orders" value="<%= @dashboard.orders %>" />
      <ul id="jquery-ui-sortable">
          <% @dashboard.snipets.each do |snipet| %>
          <li class="snipet ui-state-default">
            <div class="item">/snipets/<%= snipet._id %></div>
          </li>
          <% end %>
      </ul>
    </div>
    <div style="clear: both;"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Atlus</title>
  <link href="http://fonts.googleapis.com/css?family=Lobster:regular" rel="stylesheet" type="text/css" >
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>Atlus</h1>
    <ul>
      <li><%= link_to("Home", :dashboards) %></li>
      <li><%= link_to("Snipet", :snipets) %></li>
    </ul>
  </header>
<%= yield %>

</body>
</html>

app/views/snipets/_form.html.erb
<%= form_for(@snipet) do |f| %>
  <% if @snipet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snipet.errors.count, "error") %> prohibited this snipet from being saved:</h2>

      <ul>
      <% @snipet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :query %><br />
    <%= f.text_area :query %>
    <div id="query"></div>
  </div>
  <div class="field">
    <label for="snipet_charTtype">Chart Type</label><br />
    <%= f.select :chartType, [["Horizon Bar Chart", "horizonBar"], ["PI Chart", "pi"], ["Line Chart", "line"]] %>
  </div>
  <div class="field">
    <%= f.label :isTableVisible %><br />
    <%= f.check_box :isTableVisible %>
  </div>
  <div class="field">
    <%= f.label :isChartVisible %><br />
    <%= f.check_box :isChartVisible %>
  </div>
  <div class="field">
    <%= f.label :width %><br />
    <%= f.text_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :scale %><br />
    <%= f.text_field :scale %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snipets/edit.html.erb
<h1>Editing snipet</h1>

<%= render 'form' %>

<%= link_to 'Show', @snipet %> |
<%= link_to 'Back', snipets_path %>

app/views/snipets/index.html.erb
<h1>Listing snipets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>ChartType</th>
    <th>Table Visible</th>
    <th>Chart Visible</th>
    <th></th>
    <th></th>
  </tr>

<% @snipets.each do |snipet| %>
  <tr>
    <td><%= snipet.name %></td>
    <td><%= snipet.chartType %></td>
    <td><%= snipet.isTableVisible %></td>
    <td><%= snipet.isChartVisible %></td>
    <td><%= link_to 'Show', snipet %></td>
    <td><%= link_to 'Destroy', snipet, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Snipet', new_snipet_path %>

app/views/snipets/new.html.erb
<h1>New snipet</h1>

<%= render 'form' %>

<%= link_to 'Back', snipets_path %>

app/views/snipets/show.html.erb
<p>
  <p id="notice"><%= notice %></p>
  <%= render 'form' %>
</p>

<h1>Result:</h1>
<p>
<%= p @data %>
</p>
<h1>Preview:</h1>
<article class="snipet">
  <style type="text/css">
    .container {
      width : <%= @snipet.width %>px;
      height: <%= @snipet.height %>px;
      margin: 8px;
    }
  </style>
 
  <h1><%= @snipet.name %></h1>
  <table class="<%= (@snipet.isTableVisible== false) ? "hidden" : "" %>">
     <%=raw @table_recods %>
  </table>
  <div class="container <%= (@snipet.isChartVisible== false) ? "hidden" : "" %>"></div>
  <input type="hidden" class="chartType" value="<%= @snipet.chartType %>" />
  <input type="hidden" class="scale" value="<%= @snipet.scale %>" />
  <input type="hidden" class="name" value="<%= @snipet.name %>" />
</article>